import type { Metadata } from "next"
import "../globals.css"
import Navigation from "@/components/nav/Navigation"
import { Poppins } from "next/font/google"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins"
})

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru" className={poppins.variable}>
      <body className="lg:px-0">
        <Navigation />
        {children}
      </body>
    </html>
  )
}
